FROM golang:1.13 AS builder

WORKDIR $GOPATH/src/distributedSearchEngine/
COPY . .

RUN GO111MODULE=on
RUN go mod download all
RUN CGO_ENABLED=0 GOARCH=amd64 GOOS=linux \
    go build -o /go/bin/linkgraph ./services/linkgraph/main.go


FROM alpine:3.10
RUN apk update && apk add ca-certificates bash && rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/linkgraph /go/bin/linkgraph

ENTRYPOINT ["/go/bin/linkgraph"]
