apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  backend:
    serviceName: frontend
    servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    name: web
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        imagePullPolicy: Always
        image: jinayshah7/frontend:latest
        env:
          - name: LINK_REPOSITORY_URL
            value: "link-repository:8080"
          - name: DOCUMENT_REPOSITORY_URL
            value: "document-repository:8080"
        ports:
        - containerPort: 8080
          name: www
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 50m
