apiVersion: apps/v1
kind: Deployment
metadata:
  name: page-hash-repository 
  labels:
    app: page-hash-repository 
spec:
  selector:
    matchLabels:
      app: page-hash-repository 
  replicas: 1
  template:
    metadata:
      labels:
        app: page-hash-repository 
    spec:
      containers:
      - name: page-hash-repository 
        imagePullPolicy: Always
        image: jinayshah7/page-hash-repository:latest
        env:
          - name: SOURCE_TOPIC
            value: source_topic_name
          - name: DESTINATION_TOPIC
            value: destination_topic_name
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 50m
