// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.15.2
// source: documentRepository.proto

package documentRepository

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchQuery_Type int32

const (
	SearchQuery_MATCH  SearchQuery_Type = 0
	SearchQuery_PHRASE SearchQuery_Type = 1
)

// Enum value maps for SearchQuery_Type.
var (
	SearchQuery_Type_name = map[int32]string{
		0: "MATCH",
		1: "PHRASE",
	}
	SearchQuery_Type_value = map[string]int32{
		"MATCH":  0,
		"PHRASE": 1,
	}
)

func (x SearchQuery_Type) Enum() *SearchQuery_Type {
	p := new(SearchQuery_Type)
	*p = x
	return p
}

func (x SearchQuery_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchQuery_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_documentRepository_proto_enumTypes[0].Descriptor()
}

func (SearchQuery_Type) Type() protoreflect.EnumType {
	return &file_documentRepository_proto_enumTypes[0]
}

func (x SearchQuery_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchQuery_Type.Descriptor instead.
func (SearchQuery_Type) EnumDescriptor() ([]byte, []int) {
	return file_documentRepository_proto_rawDescGZIP(), []int{1, 0}
}

type Document struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocumentId []byte                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Url        string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Title      string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content    string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	IndexedAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=indexed_at,json=indexedAt,proto3" json:"indexed_at,omitempty"`
}

func (x *Document) Reset() {
	*x = Document{}
	if protoimpl.UnsafeEnabled {
		mi := &file_documentRepository_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_documentRepository_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_documentRepository_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetDocumentId() []byte {
	if x != nil {
		return x.DocumentId
	}
	return nil
}

func (x *Document) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Document) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Document) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Document) GetIndexedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IndexedAt
	}
	return nil
}

type SearchQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       SearchQuery_Type `protobuf:"varint,1,opt,name=type,proto3,enum=documentRepository.SearchQuery_Type" json:"type,omitempty"`
	Expression string           `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	Offset     uint64           `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *SearchQuery) Reset() {
	*x = SearchQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_documentRepository_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchQuery) ProtoMessage() {}

func (x *SearchQuery) ProtoReflect() protoreflect.Message {
	mi := &file_documentRepository_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchQuery.ProtoReflect.Descriptor instead.
func (*SearchQuery) Descriptor() ([]byte, []int) {
	return file_documentRepository_proto_rawDescGZIP(), []int{1}
}

func (x *SearchQuery) GetType() SearchQuery_Type {
	if x != nil {
		return x.Type
	}
	return SearchQuery_MATCH
}

func (x *SearchQuery) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *SearchQuery) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//	*SearchResult_DocCount
	//	*SearchResult_Doc
	Result isSearchResult_Result `protobuf_oneof:"result"`
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_documentRepository_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_documentRepository_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_documentRepository_proto_rawDescGZIP(), []int{2}
}

func (m *SearchResult) GetResult() isSearchResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *SearchResult) GetDocCount() uint64 {
	if x, ok := x.GetResult().(*SearchResult_DocCount); ok {
		return x.DocCount
	}
	return 0
}

func (x *SearchResult) GetDoc() *Document {
	if x, ok := x.GetResult().(*SearchResult_Doc); ok {
		return x.Doc
	}
	return nil
}

type isSearchResult_Result interface {
	isSearchResult_Result()
}

type SearchResult_DocCount struct {
	DocCount uint64 `protobuf:"varint,1,opt,name=doc_count,json=docCount,proto3,oneof"`
}

type SearchResult_Doc struct {
	Doc *Document `protobuf:"bytes,2,opt,name=doc,proto3,oneof"`
}

func (*SearchResult_DocCount) isSearchResult_Result() {}

func (*SearchResult_Doc) isSearchResult_Result() {}

type SetPageRankScoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocumentId    []byte  `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	PageRankScore float64 `protobuf:"fixed64,2,opt,name=page_rank_score,json=pageRankScore,proto3" json:"page_rank_score,omitempty"`
}

func (x *SetPageRankScoreRequest) Reset() {
	*x = SetPageRankScoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_documentRepository_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPageRankScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPageRankScoreRequest) ProtoMessage() {}

func (x *SetPageRankScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_documentRepository_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPageRankScoreRequest.ProtoReflect.Descriptor instead.
func (*SetPageRankScoreRequest) Descriptor() ([]byte, []int) {
	return file_documentRepository_proto_rawDescGZIP(), []int{3}
}

func (x *SetPageRankScoreRequest) GetDocumentId() []byte {
	if x != nil {
		return x.DocumentId
	}
	return nil
}

func (x *SetPageRankScoreRequest) GetPageRankScore() float64 {
	if x != nil {
		return x.PageRankScore
	}
	return 0
}

type PageRankScore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageRankScore float64 `protobuf:"fixed64,1,opt,name=page_rank_score,json=pageRankScore,proto3" json:"page_rank_score,omitempty"`
}

func (x *PageRankScore) Reset() {
	*x = PageRankScore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_documentRepository_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageRankScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRankScore) ProtoMessage() {}

func (x *PageRankScore) ProtoReflect() protoreflect.Message {
	mi := &file_documentRepository_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRankScore.ProtoReflect.Descriptor instead.
func (*PageRankScore) Descriptor() ([]byte, []int) {
	return file_documentRepository_proto_rawDescGZIP(), []int{4}
}

func (x *PageRankScore) GetPageRankScore() float64 {
	if x != nil {
		return x.PageRankScore
	}
	return 0
}

type DocumentID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocumentId []byte `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
}

func (x *DocumentID) Reset() {
	*x = DocumentID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_documentRepository_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocumentID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentID) ProtoMessage() {}

func (x *DocumentID) ProtoReflect() protoreflect.Message {
	mi := &file_documentRepository_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentID.ProtoReflect.Descriptor instead.
func (*DocumentID) Descriptor() ([]byte, []int) {
	return file_documentRepository_proto_rawDescGZIP(), []int{5}
}

func (x *DocumentID) GetDocumentId() []byte {
	if x != nil {
		return x.DocumentId
	}
	return nil
}

var File_documentRepository_proto protoreflect.FileDescriptor

var file_documentRepository_proto_rawDesc = []byte{
	0x0a, 0x18, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x64, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa8, 0x01, 0x0a,
	0x08, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a,
	0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x39, 0x0a, 0x0a,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x65, 0x64, 0x41, 0x74, 0x22, 0x9e, 0x01, 0x0a, 0x0b, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x38, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x51, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x1d, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x50, 0x48, 0x52, 0x41, 0x53, 0x45, 0x10, 0x01, 0x22, 0x69, 0x0a, 0x0c, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1d, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x08, 0x64,
	0x6f, 0x63, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x03, 0x64, 0x6f, 0x63, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x48, 0x00, 0x52, 0x03, 0x64, 0x6f, 0x63, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x62, 0x0a, 0x17, 0x53, 0x65, 0x74, 0x50, 0x61, 0x67, 0x65, 0x52, 0x61,
	0x6e, 0x6b, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0a, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x26, 0x0a, 0x0f, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x70, 0x61, 0x67, 0x65, 0x52, 0x61,
	0x6e, 0x6b, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x37, 0x0a, 0x0d, 0x50, 0x61, 0x67, 0x65, 0x52,
	0x61, 0x6e, 0x6b, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x70, 0x61, 0x67, 0x65,
	0x5f, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0d, 0x70, 0x61, 0x67, 0x65, 0x52, 0x61, 0x6e, 0x6b, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x22, 0x2d, 0x0a, 0x0a, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x1f,
	0x0a, 0x0b, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0a, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x32,
	0xd8, 0x02, 0x0a, 0x12, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x43, 0x0a, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x1c, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x6f, 0x72, 0x79, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x1c, 0x2e,
	0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f,
	0x72, 0x79, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x4d, 0x0a, 0x06, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x1f, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x51, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x20, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x30, 0x01, 0x12, 0x57, 0x0a, 0x10, 0x53, 0x65,
	0x74, 0x50, 0x61, 0x67, 0x65, 0x52, 0x61, 0x6e, 0x6b, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x2b,
	0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x6f, 0x72, 0x79, 0x2e, 0x53, 0x65, 0x74, 0x50, 0x61, 0x67, 0x65, 0x52, 0x61, 0x6e, 0x6b, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x55, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x61, 0x67, 0x65, 0x52, 0x61,
	0x6e, 0x6b, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1e, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x44, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x1a, 0x21, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x50, 0x61, 0x67,
	0x65, 0x52, 0x61, 0x6e, 0x6b, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x42, 0x17, 0x5a, 0x15, 0x2e, 0x2f,
	0x3b, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x6f, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_documentRepository_proto_rawDescOnce sync.Once
	file_documentRepository_proto_rawDescData = file_documentRepository_proto_rawDesc
)

func file_documentRepository_proto_rawDescGZIP() []byte {
	file_documentRepository_proto_rawDescOnce.Do(func() {
		file_documentRepository_proto_rawDescData = protoimpl.X.CompressGZIP(file_documentRepository_proto_rawDescData)
	})
	return file_documentRepository_proto_rawDescData
}

var file_documentRepository_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_documentRepository_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_documentRepository_proto_goTypes = []interface{}{
	(SearchQuery_Type)(0),           // 0: documentRepository.SearchQuery.Type
	(*Document)(nil),                // 1: documentRepository.Document
	(*SearchQuery)(nil),             // 2: documentRepository.SearchQuery
	(*SearchResult)(nil),            // 3: documentRepository.SearchResult
	(*SetPageRankScoreRequest)(nil), // 4: documentRepository.SetPageRankScoreRequest
	(*PageRankScore)(nil),           // 5: documentRepository.PageRankScore
	(*DocumentID)(nil),              // 6: documentRepository.DocumentID
	(*timestamppb.Timestamp)(nil),   // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 8: google.protobuf.Empty
}
var file_documentRepository_proto_depIdxs = []int32{
	7, // 0: documentRepository.Document.indexed_at:type_name -> google.protobuf.Timestamp
	0, // 1: documentRepository.SearchQuery.type:type_name -> documentRepository.SearchQuery.Type
	1, // 2: documentRepository.SearchResult.doc:type_name -> documentRepository.Document
	1, // 3: documentRepository.DocumentRepository.Index:input_type -> documentRepository.Document
	2, // 4: documentRepository.DocumentRepository.Search:input_type -> documentRepository.SearchQuery
	4, // 5: documentRepository.DocumentRepository.SetPageRankScore:input_type -> documentRepository.SetPageRankScoreRequest
	6, // 6: documentRepository.DocumentRepository.GetPageRankScore:input_type -> documentRepository.DocumentID
	1, // 7: documentRepository.DocumentRepository.Index:output_type -> documentRepository.Document
	3, // 8: documentRepository.DocumentRepository.Search:output_type -> documentRepository.SearchResult
	8, // 9: documentRepository.DocumentRepository.SetPageRankScore:output_type -> google.protobuf.Empty
	5, // 10: documentRepository.DocumentRepository.GetPageRankScore:output_type -> documentRepository.PageRankScore
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_documentRepository_proto_init() }
func file_documentRepository_proto_init() {
	if File_documentRepository_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_documentRepository_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Document); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_documentRepository_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_documentRepository_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_documentRepository_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPageRankScoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_documentRepository_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageRankScore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_documentRepository_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocumentID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_documentRepository_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*SearchResult_DocCount)(nil),
		(*SearchResult_Doc)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_documentRepository_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_documentRepository_proto_goTypes,
		DependencyIndexes: file_documentRepository_proto_depIdxs,
		EnumInfos:         file_documentRepository_proto_enumTypes,
		MessageInfos:      file_documentRepository_proto_msgTypes,
	}.Build()
	File_documentRepository_proto = out.File
	file_documentRepository_proto_rawDesc = nil
	file_documentRepository_proto_goTypes = nil
	file_documentRepository_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DocumentRepositoryClient is the client API for DocumentRepository service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DocumentRepositoryClient interface {
	Index(ctx context.Context, in *Document, opts ...grpc.CallOption) (*Document, error)
	Search(ctx context.Context, in *SearchQuery, opts ...grpc.CallOption) (DocumentRepository_SearchClient, error)
	SetPageRankScore(ctx context.Context, in *SetPageRankScoreRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetPageRankScore(ctx context.Context, in *DocumentID, opts ...grpc.CallOption) (*PageRankScore, error)
}

type documentRepositoryClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentRepositoryClient(cc grpc.ClientConnInterface) DocumentRepositoryClient {
	return &documentRepositoryClient{cc}
}

func (c *documentRepositoryClient) Index(ctx context.Context, in *Document, opts ...grpc.CallOption) (*Document, error) {
	out := new(Document)
	err := c.cc.Invoke(ctx, "/documentRepository.DocumentRepository/Index", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentRepositoryClient) Search(ctx context.Context, in *SearchQuery, opts ...grpc.CallOption) (DocumentRepository_SearchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DocumentRepository_serviceDesc.Streams[0], "/documentRepository.DocumentRepository/Search", opts...)
	if err != nil {
		return nil, err
	}
	x := &documentRepositorySearchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DocumentRepository_SearchClient interface {
	Recv() (*SearchResult, error)
	grpc.ClientStream
}

type documentRepositorySearchClient struct {
	grpc.ClientStream
}

func (x *documentRepositorySearchClient) Recv() (*SearchResult, error) {
	m := new(SearchResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *documentRepositoryClient) SetPageRankScore(ctx context.Context, in *SetPageRankScoreRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/documentRepository.DocumentRepository/SetPageRankScore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentRepositoryClient) GetPageRankScore(ctx context.Context, in *DocumentID, opts ...grpc.CallOption) (*PageRankScore, error) {
	out := new(PageRankScore)
	err := c.cc.Invoke(ctx, "/documentRepository.DocumentRepository/GetPageRankScore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentRepositoryServer is the server API for DocumentRepository service.
type DocumentRepositoryServer interface {
	Index(context.Context, *Document) (*Document, error)
	Search(*SearchQuery, DocumentRepository_SearchServer) error
	SetPageRankScore(context.Context, *SetPageRankScoreRequest) (*emptypb.Empty, error)
	GetPageRankScore(context.Context, *DocumentID) (*PageRankScore, error)
}

// UnimplementedDocumentRepositoryServer can be embedded to have forward compatible implementations.
type UnimplementedDocumentRepositoryServer struct {
}

func (*UnimplementedDocumentRepositoryServer) Index(context.Context, *Document) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Index not implemented")
}
func (*UnimplementedDocumentRepositoryServer) Search(*SearchQuery, DocumentRepository_SearchServer) error {
	return status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedDocumentRepositoryServer) SetPageRankScore(context.Context, *SetPageRankScoreRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPageRankScore not implemented")
}
func (*UnimplementedDocumentRepositoryServer) GetPageRankScore(context.Context, *DocumentID) (*PageRankScore, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPageRankScore not implemented")
}

func RegisterDocumentRepositoryServer(s *grpc.Server, srv DocumentRepositoryServer) {
	s.RegisterService(&_DocumentRepository_serviceDesc, srv)
}

func _DocumentRepository_Index_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Document)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentRepositoryServer).Index(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/documentRepository.DocumentRepository/Index",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentRepositoryServer).Index(ctx, req.(*Document))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentRepository_Search_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchQuery)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DocumentRepositoryServer).Search(m, &documentRepositorySearchServer{stream})
}

type DocumentRepository_SearchServer interface {
	Send(*SearchResult) error
	grpc.ServerStream
}

type documentRepositorySearchServer struct {
	grpc.ServerStream
}

func (x *documentRepositorySearchServer) Send(m *SearchResult) error {
	return x.ServerStream.SendMsg(m)
}

func _DocumentRepository_SetPageRankScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPageRankScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentRepositoryServer).SetPageRankScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/documentRepository.DocumentRepository/SetPageRankScore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentRepositoryServer).SetPageRankScore(ctx, req.(*SetPageRankScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentRepository_GetPageRankScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentRepositoryServer).GetPageRankScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/documentRepository.DocumentRepository/GetPageRankScore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentRepositoryServer).GetPageRankScore(ctx, req.(*DocumentID))
	}
	return interceptor(ctx, in, info, handler)
}

var _DocumentRepository_serviceDesc = grpc.ServiceDesc{
	ServiceName: "documentRepository.DocumentRepository",
	HandlerType: (*DocumentRepositoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Index",
			Handler:    _DocumentRepository_Index_Handler,
		},
		{
			MethodName: "SetPageRankScore",
			Handler:    _DocumentRepository_SetPageRankScore_Handler,
		},
		{
			MethodName: "GetPageRankScore",
			Handler:    _DocumentRepository_GetPageRankScore_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Search",
			Handler:       _DocumentRepository_Search_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "documentRepository.proto",
}
