name = "serverless-search-engine"
type = "javascript"
account_id = "${CF_ACCOUNT_ID}"
workers_dev = true

[workers_dev]
route = "https://jinay.io/dev/*"

[env.production]
name = "serverless-search-engine"
account_id = "${CF_ACCOUNT_ID}"
workers = ["LinkFetcher", "PageRenderer", "PageProcessor", "PageSaver", "PageRankQueuer", "PageRankProcessor"]
workers_dev = false
route = "https://jinay.io/prod/*"

[build]
command = "npm run build"
output_dir = "dist"

kv_namespaces = [
  {binding = "VisitedPageHashes", id = "<kv-namespace-1-id>"},
  {binding = "PageRankState", id = "<kv-namespace-2-id>"}
]

[queues]
FetchedLinks = { max_size = 100 }
RenderedPages = { max_size = 100 }
ProcessedPages = { max_size = 100 }
PageRankeQueue = { max_size = 100 }
